# Generated by Django 4.2 on 2023-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('L', 'Laptop'), ('AL', 'Accesories Laptop'), ('PS', 'Printer & Scanner')], max_length=2),
        ),
    ]
